#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: ['GET', 'POST']

user_list:
    path: /users
    controller: App\Controller\UserListController::userList
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_media_index:
    path: /media
    controller: App\Controller\MediaController::index
    methods: [GET]
app_market_index:
    path: /market
    controller: App\Controller\MarketController::index
    methods: [GET]
user_delete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete

app_user_index:
    path: /users
    controller: 'App\Controller\UserListController::index'




user_delete_list:
    path: '/user/{id}'
    controller: 'App\Controller\UserListController::deleteUser'
    methods: ['POST']


user_search:
    path: /votre-url-de-recherche
    controller: 'App\Controller\UserController::search'



   

